config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls', namespace='home')),
]

home/urls.py
from django.urls import path
from . import views
app_name = 'home'

urlpatterns = [
    path('' , views.show_post , name='show') ,
    path('detail/<int:id>/' , views.show_detail_post , name='detail') ,
    path('create/' , views.create_post , name='create') ,
]

home/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    STATUS =(
        ('pub' , 'انتشار یافته'),
        ('drf' , 'پیش نمایش'),
    )
    title = models.CharField(max_length=50)
    information = models.TextField(max_length=500,null=True,blank=True)
    datetime_create = models.DateTimeField(auto_now_add=True)
    datetime_update = models.DateTimeField(auto_now=True)
    status = models.CharField(choices=STATUS , max_length=3)

    def __str__(self):
        return self.title

home/views.py
from django.shortcuts import render
from .models import *
# Create your views here.

def show_post(request):
    posts = Post.objects.filter(status='pub')
    return render(request , 'home.html' , {'posts':posts})

def show_detail_post(request, id):
    post = Post.objects.get(id=id)
    return render(request , 'detail.html' , {'post':post})


def create_post(request):
    print(request.POST)

    if request.method == 'POST' :
        print(request.POST.get('title'))
        print(request.POST.get('information'))

        a = request.POST.get('title')
        b = request.POST.get('information')
        Post.objects.create(title = a , information= b , status='drf')
    else :
        pass
    return render(request , 'create_post.html')

templates/_base.html
<!doctype html>
<html lang="en" dir="rtl">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{% block page_title %}{% endblock page_title %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">i3center.com</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'home:show' %}">خانه</a>
                <a class="nav-link" href="{% url 'home:create' %}">پست جدید</a>
            </div>
        </div>
        <div class="mx-2 text-white">Welcome</div>
    </div>
</nav>

<div class="container-fluid bg-info">
    <div class="row py-3">
        <div class="col-md-8 col-md-10 mx-auto">
            <h3 class="my-4 mt-3 text-white">این وبلاگ تمرین پستهای دیجنگو است</h3>
            <p class="text-light">این وبلاگ تمرین پستهای دیجنگو است</p>
        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="row">
        <div class="col-9">
           {% block content %}
            {% endblock %}
        </div>
        <div class="col-3">

                <div class="card my-4">
                    <h5 class="card-header">About</h5>
                    <div class="card-body">
                        <p class="card-text">We love python and django. So we created a blog site to share our
                            thoughts</p>
                        <a href="#"
                           class="btn btn-sm btn-danger">
                            More...
                        </a>
                    </div>
                </div>

        </div>
    </div>
</div>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>

templates/create_post.html
{% extends '_base.html' %}
{% block page_title %}
	صفحه ایجاد پست
{% endblock %}
{% block content %}
     <div class="card shadow my-3 p-5">
                <h3> ایجاد پست:</h3>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group py-2">
                        <label class="py-1">Enter post title</label>
                        <input type="text" class="form-control" placeholder="e.g. Some Title" name="title">
                    </div>
                    <div class="form-group py-2">
                        <label class="py-1">Enter post text:</label>
                        <textarea class="form-control" name="information" rows="8" placeholder="Enter your post text here..."></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
{% endblock %}

templates/detail.html
{% extends '_base.html' %}
{% block page_title %}
    صفحه جزییات
{% endblock %}
{% block content %}
	 <div class="card shadow my-3 p-5">
                <h1>{{ post.title }}</h1>
                <p class="small text-muted mt-2">By: {{ post.datetime_create }}</p>
                <p class="mt-2">{{ post.information }}</p>
            </div>

            <div class="card shadow my-3 p-5">
                <h3>Comments:</h3>
                    No comments yet! Be the first one.
            </div>

            <div class="card shadow my-3 p-5">
                <h3>Add new comment:</h3>
                <form method="POST">
                    <div class="form-group py-2">
                        <label class="py-1" for="author_name">Enter your name:</label>
                        <input type="text" class="form-control" placeholder="e.g. John Doe" name="author_name">
                    </div>
                    <div class="form-group py-2">
                        <label class="py-1" for="email">Your Email:</label>
                        <input type="email" class="form-control" placeholder="example@gmail.com" name="email">
                    </div>
                    <div class="form-group py-2">
                        <label class="py-1" for="comment_text">Comment text:</label>
                        <textarea class="form-control" name="text" rows="3" placeholder="Enter your comment text here..."></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
{% endblock %}

templates/home.html
{% extends '_base.html' %}
{% block page_title %}
	صفحه اصلی
{% endblock %}
{% block content %}
{% for item in posts %}
	 <div class="card shadow-sm my-3">
                <div class="card-body">

                    <h5 class="card-title">{{ item.title }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted small py-2">{{ item.datetime_update }}</h6>

                    <a href="{% url 'home:detail' item.id %}" class="btn btn-sm btn-success">Read More</a>

                </div>
            </div>
    {% endfor %}
{% endblock %}